@startuml
scale 1.05
skinparam defaultFontName Arial
skinparam defaultFontSize 20
skinparam shadowing false
skinparam dpi 180
left to right direction

title Mo hinh MVC tong quat

rectangle "View" as View
rectangle "Controller" as Controller
rectangle "Model" as Model

View --> Controller : gui yeu cau
Controller --> Model : xu ly nghiep vu
Model --> View : cap nhat du lieu

@enduml
