@startuml
scale 0.95
skinparam defaultFontName Arial
skinparam defaultFontSize 16
skinparam shadowing false
skinparam dpi 180
skinparam linetype ortho
hide circle

title Bieu do thuc the lien ket cua he thong ShipMaster

entity users {
  * uid : string
  --
  fullName : string
  email : string
  role : string
}

entity customers {
  * uid : string
  --
  phone : string
  myreferralCode : string
}

entity ship {
  * id : string
  --
  uid : string
  name : string
  registration_number : string
}

entity workShop {
  * id : string
  --
  name : string
  ownerID : string
  location : string
}

entity employees {
  * id : string
  --
  workShopID : string
  Expertise : string
}

entity repairOrder {
  * id : string
  --
  uid : string
  shipId : string
  workshopId : string
  inspectorId : string
  invoiceId : string
  Status : string
}

entity material {
  * id : string
  --
  Name : string
  Unit : string
  Price : number
}

entity repairordermaterial {
  * id : string
  --
  RepairOrder_ID : string
  Material_ID : string
  QuantityUsed : number
}

entity repairorderlabor {
  * id : string
  --
  RepairOrder_ID : string
  Employee_ID : string
  Days : number
}

entity invoice {
  * id : string
  --
  RepairOrder_ID : string
  TotalAmount : number
  RemainingAmount : number
  PaymentStatus : string
}

entity payment {
  * id : string
  --
  Invoice_ID : string
  Amount : number
  PaymentMethod : string
}

users ||--o| customers
customers ||--o{ ship
customers ||--o{ repairOrder
ship ||--o{ repairOrder
workShop ||--o{ repairOrder
workShop ||--o{ employees
repairOrder ||--o{ repairordermaterial
material ||--o{ repairordermaterial
repairOrder ||--o{ repairorderlabor
employees ||--o{ repairorderlabor
repairOrder ||--o| invoice
invoice ||--o{ payment
users ||--o{ repairOrder : inspector
users ||--o{ workShop : owner

@enduml
